### ISSUE TITLE
milk command with NameError: uninitialized constant Groonga::Posting

### ISSUE THREAD

**Issue by wkentaro** [ongaeshi/milkode#78]
```
% milk
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require': uninitialized constant Groonga::Posting (NameError)
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/milkode-1.8.7/lib/milkode/database/groonga_database.rb:9:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/milkode-1.8.7/lib/milkode/cdstk/cdstk.rb:24:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/milkode-1.8.7/lib/milkode/cli.rb:4:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/milkode-1.8.7/bin/milk:7:in `<top (required)>'
	from /usr/local/bin/milk:23:in `load'
	from /usr/local/bin/milk:23:in `<main>'

% brew install groonga
Warning: groonga-5.0.7 already installed

% gem list | grep milkode
milkode (1.8.7)

% gem list | grep roonga
groonga (1.0.0)
groonga-client (0.1.9)
groonga-command (1.1.3)
rroonga (5.0.5)
```

**Comment by wkentaro** [comment]
**Environment**

* OS X 10.10 Yosemite
* Homebrew
* rubygem installed via `brew install ruby`

**Comment by ongaeshi** [comment]
`milk init` has been executed? (Error is bad when database does not exist...)

```
$ milk init --default
create     : /Users/auser/.milkode/milkode.yaml
create     : /Users/auser/.milkode/db/milkode.db created.
```

**Comment by wkentaro** [comment]
Yeah, I had same error:
```
% milk init --default
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require': uninitialized constant Groonga::Posting (NameError)
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/milkode-1.8.7/lib/milkode/database/groonga_database.rb:9:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/milkode-1.8.7/lib/milkode/cdstk/cdstk.rb:24:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/milkode-1.8.7/lib/milkode/cli.rb:4:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/milkode-1.8.7/bin/milk:7:in `<top (required)>'
	from /usr/local/bin/milk:23:in `load'
	from /usr/local/bin/milk:23:in `<main>'% milk init --default
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require': uninitialized constant Groonga::Posting (NameError)
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/milkode-1.8.7/lib/milkode/database/groonga_database.rb:9:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/milkode-1.8.7/lib/milkode/cdstk/cdstk.rb:24:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/milkode-1.8.7/lib/milkode/cli.rb:4:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/milkode-1.8.7/bin/milk:7:in `<top (required)>'
	from /usr/local/bin/milk:23:in `load'
	from /usr/local/bin/milk:23:in `<main>'
```

**Comment by ongaeshi** [comment]
Thanks. Probably I think that it becomes to move if you drop a version of Groonga and Rroonga. 

It will fix to move even 5.0.7.

**Comment by ongaeshi** [comment]
It is one of my local environment. (Windows).

```
$ gem list
milkode (1.8.7, 1.8.5, 1.8.0)
rroonga (5.0.0 x86-mingw32)
```

**Comment by kenhys** [comment]
I've heard the similar report before. It may have something to do with older rubygems version.
https://osdn.jp/projects/groonga/lists/archive/dev/2015-July/003347.html

**Comment by ongaeshi** [comment]
Thanks @kenhys !

**Comment by wkentaro** [comment]
Thanks, it is fixed.

```
gem install rubygems-update
update_ruby_gems
```
